### ISSUE TITLE
Is there going to be a default implementation of TwinsClient?

### ISSUE THREAD

**Issue by mahdighorbanpour** [telstra/DigitalTwins-CodeFirst-dotnet#18]
Hi,
You have defined an interface and an abstract class to manage the twins. However, there is no default implementation in the code. Do you have any plans to implement one? Thank you

**Comment by kavink98** [comment]
No these classes are redundant and are soon to be removed, just waiting for a colleague to merge my pull requests

**Comment by mahdighorbanpour** [comment]
@kavink98 Thanks for the prompt reply. Please forgive me for my dummy question though, I can see the library can create DTDL models and also can produce a twin (the json string). However, I can't find the way you communicate to ADT and upload the models and create digital twins. Could you please let me know, which class is doing these stuff?
Thank you

**Comment by sgryphon** [comment]
Of interest -- I am working on an example to do this, to replicate the "chocolate factory" from the ADT samples.

I haven't got up to that point yet, of using the client, but have the basic model and then passed it to the Microsoft.Azure.DigitalTwins.Parser to validate. That raised a bunch of issues that I submitted PRs for.

There is a bit more to do, with setting up the scripts/templates to create Azure resources and then use the Microsoft digital twins client to push them up, but I am aiming to get an end-to-end example working at some point.

I will post an update when I have made some progress.

**Comment by kavink98** [comment]
@mahdighorbanpour sorry for the late response but for communication with ADT you will have to use the Azure client. Documentation can be found [here](https://docs.microsoft.com/en-us/dotnet/api/azure.digitaltwins.core?view=azure-dotnet)

**Comment by sgryphon** [comment]
I have an example ready in a pull request on how to use the Azure client to upload the generated twins. If you want to look at it before it is merged, my branch is: https://github.com/sgryphon/DigitalTwins-CodeFirst-dotnet/tree/feature/factory-example
