### ISSUE TITLE
Issue with DateTime property type and nullables

### ISSUE THREAD

**Issue by mahdighorbanpour** [telstra/DigitalTwins-CodeFirst-dotnet#2]
Hi, 
I am experimenting with the library and appreciate a lot your project. I found two issues during my experiment and also found the fix. 

- Properties with type of DateTime will end up with no schema in the output DTDL model. To address the issue, we need to add the missing type map in ModelProperty.Factory.cs for SchemaMap variable `{ typeof(DateTime), "dateTime" },`
- Nullable properties seems to be working fine, however a nullable of DateTime still will have no schema in the output. To fix it, in the same file, I made these changes:

internal static object SchemaFromType(PropertyInfo info)
        {
            var propertyType = info.PropertyType;
            **var nullableType = Nullable.GetUnderlyingType(propertyType);**
            if (SchemaMap.ContainsKey(propertyType))  
                return SchemaMap[propertyType];
            **else if(nullableType != null && SchemaMap.ContainsKey(nullableType))
            {
                return SchemaMap[nullableType];
            }**
            else if .....

**Comment by sgryphon** [comment]
Nice catch, and a good fix.

I have added a pull request to fix the issue, using similar to the code that you suggested, and including test case to handle the DTDL dateTime schema type. I also added an override to allow schema override via the property for types such as "date", that are not yet supported directly in dotnet.

Note that the DTDL specification defines dateTime as the date-time construct from RFC 3339, which includes full-time, that includes time-offset. The correct matching type in dotnet is `DateTimeOffset`.

Further, the Microsoft recommendation is that you should _"consider `DateTimeOffset` as the default date and time type for application development"_ (See https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime#the-datetimeoffset-structure)

The `DateTime` struct is almost never the correct type to use. It can introduce subtle time related bugs that can be hard to find. I suggest you do not use it.

**Comment by mahdighorbanpour** [comment]
Hi @sgryphon,
Thank you for looking into it and the detailed explanations.

**Comment by kavink98** [comment]
The pull request has been merged. Closing this issue now
