### ISSUE TITLE
Semantic type and units are not working

### ISSUE THREAD

**Issue by sgryphon** [telstra/DigitalTwins-CodeFirst-dotnet#8]
A telemetry type attribute with Unit and SemanticType does not work.

Example property:

```
        [TwinTelemetry(Unit = "degreeCelsius", SemanticType = "Temperature")]
        public double? Temperature { get; set; }
```

Validating with the model parser gives two errors:

1. dtmi:factoryexample:models:factoryfloor;1 has 'contents' value with name 'temperature' which does not have a @type that allows property 'SemanticType'. Remove property 'SemanticType' or correct if misspelled.
2. dtmi:factoryexample:models:factoryfloor;1 has 'contents' value with name 'temperature' which does not have a @type that allows property 'Unit'. Remove property 'Unit' or correct if misspelled.

The generated DTDL that caused the error is:

```
    {
      "SemanticType": "Temperature",
      "Unit": "degreeCelsius",
      "@type": "Telemetry",
      "name": "temperature",
      "schema": "double"
    }
```

According to the DTDLv2 specification, it should be the following (See examples at: https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#telemetry-examples)

```
    {
      "@type": ["Telemetry", "Temperature"],
      "name": "temperature",
      "schema": "double",
      "unit": "degreeCelsius"
    }
```

Other things to note:
* Semantic types should also apply to Properties (not just Telemetry).
* The list of valid semantic types and units is in the DTDLv2 specification

**Comment by kavink98** [comment]
Can this issue now be closed?

**Comment by sgryphon** [comment]
Yes, can close - now have working semantic types, and on Telemetry and Properties, and constants for all the defined types and units (from the DTDL specification).
