### ISSUE TITLE
DisplayName property on TwinRelationshipAttribute doesn't work

### ISSUE THREAD

**Issue by sgryphon** [telstra/DigitalTwins-CodeFirst-dotnet#9]
Using the display name attribute as part of a relationship, e.g.

```
       [TwinRelationship(DisplayName = "Runs Production Lines", MaxMultiplicity = 500)]
        public IList<ProductionLine> RunsLines { get; } = new List<ProductionLine>();
```

Causes the following error in the ModelParser:

1. dtmi:factoryexample:models:factoryfloor;1 has 'contents' value with name 'runsLines' which does not have a @type that allows property 'DisplayName'. Remove property 'DisplayName' or correct if misspelled.

The generated DTDL is:

```
    {
      "DisplayName": "Runs Production Lines",
      "maxMultiplicity": 500,
      "minMultiplicity": 0,
      "target": "dtmi:factoryexample:models:productionline;1",
      "@type": "Relationship",
      "name": "runsLines"
    },
```

The capitalisation of displayName is incorrect; in the specification it is camelCase, like the other properties.

**Comment by kavink98** [comment]
This problem has been resolved with a simple solution however in the process another bug revealed itself once I have resolved that I will raise a PR with the fix

**Comment by sgryphon** [comment]
I have restructured some of the DTDL model classes to match the DTDLv2 spec, in my Semantic Properties branch/PR.

This moves the DisplayName attribute to a base class, as it is common across all of DTDL (see the diagram in my other branch).

**Comment by sgryphon** [comment]
This now works. The code:

```
        [TwinRelationship(DisplayName = "Runs Production Lines")]
        public IList<ProductionLine> RunsLines { get; } = new List<ProductionLine>();
```

Becomes:

```
    {
      "target": "dtmi:factoryexample:models:productionline;1",
      "name": "runsLines",
      "@type": "Relationship",
      "displayName": "Runs Production Lines"
    }
```

The `displayName` property is correctly serialised.

Note that `displayName` is common across all DTDL types, so I added it to the base class (diagram is here [https://github.com/telstra/DigitalTwins-CodeFirst-dotnet/blob/main/docs/pics/DTDLv2-structure.png](https://github.com/telstra/DigitalTwins-CodeFirst-dotnet/blob/main/docs/pics/DTDLv2-structure.png)).

(The fix also shows how min & max default values are just left blank and no unnecessarily output; and the max now works correctly).
